spring.application.name=management-api
server.port=2026

spring.datasource.username=methea
spring.datasource.password=methea
spring.datasource.url=jdbc:postgresql://localhost:5432/v2
spring.jpa.hibernate.ddl-auto=update

##Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

keystore-token-file= classpath:keystore/mgmt-api.pfx
keystore-token-password= SIeTZZY;dMY%GGz2-#He
keystore-token-alias=metheax.com
keystore-key-token-password= SIeTZZY;dMY%GGz2-#He

keystore-refresh-token-file= classpath:keystore/mgmt-api.pfx
keystore-refresh-token-password= SIeTZZY;dMY%GGz2-#He
keystore-refresh-token-alias=metheax.com
keystore-key-refresh-token-password= SIeTZZY;dMY%GGz2-#He
